collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "PS-author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "PS-post"
  - scope:
      path: ""
    values:
      layout: "PS-default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag